# Generated by Django 4.2.1 on 2023-08-12 07:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couriermanage', '0002_alter_courier_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1-768x768.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='photo_id',
            field=cloudinary.models.CloudinaryField(default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1-768x768.jpg', max_length=255, verbose_name='image'),
        ),
    ]
